[[plugins]]
repo = 'Shougo/dein.vim'

[[plugin]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  let g: hybrid_user_iTerm_colors=1
  colorscheme hybrid
  syntax on
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <Leader>c <Plug>(caw:hatpos:toggle)
  vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  let g:acp_enableAtStartup = 1
  let g:neocomplete#enable_at_startup = 1

  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#enable_camel_case = 1

  let g:neocomplete#min_keyword_length = 3

  let g:neocomplete#manual_completion_start_length = 0"

  let g:neocomplete#enable_underbar_completion = 1
  let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'scala' : $HOME . '/.vim/dict/scala.dict',
    \ }
  autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
  autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/syntastic'
