[[plugins]]
repo = 'Shougo/dein.vim'

[[plugin]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  let g: hybrid_user_iTerm_colors=1
  colorscheme hybrid
  syntax on
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <Leader>c <Plug>(caw:hatpos:toggle)
  vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/syntastic'
