[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/syntastic'
